version: '3.8'

services:
  db:
    container_name: 311-postgres
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - target: 5432
        published: ${DB_HOST_PORT}
    volumes:
      - backend_data:/var/lib/postgresql/data

  redis:
    container_name: 311-redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

  api:
    container_name: 311-api
    build: ./api
    restart: ${API_RESTART_POLICY}
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      CACHE_ENDPOINT: redis
    ports:
      - target: ${APP_PORT}
        published: ${API_HOST_PORT}
    command: gunicorn lacity_data_api.asgi:app -w 4 -k uvicorn.workers.UvicornWorker --log-level info -b 0.0.0.0:5000
    # volumes:
    #   - ./api/:/home/api
    depends_on:
      - db
      - redis

  prefect:
    container_name: 311-prefect
    build: ./prefect
    environment: 
      PREFECT__CONTEXT__SECRETS__DSN: postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    depends_on:
      - db

volumes:
  backend_data:
