# mode can be "full" (uses datasets for "data.years") or "update" (uses "data.since" as start across all datasets)
mode = "update"

# determines whether Dask should be used to parallelize the flow run
dask = true

# (!) WARNING: setting this to "true" will wipe out whatever is in the target table (e.g. 'requests')
reset_db = false  

[socrata]
host = "data.lacity.org"
token = "6b5lwk1jHSQTgx7PAVFKOOdt2"

[socrata.datasets]
"2020" = "rq3b-xjk8"
"2019" = "pvft-t768"
"2018" = "h65r-yf5i"
"2017" = "d4vt-q4t5"
"2016" = "ndkd-k878"
"2015" = "ms7h-a45h"

[data]
key = "srnumber"
target = "requests"
years = [
    "2020",
    "2019"
    ]
since = "2020-09-20T01:39:13"
views = [
    "service_requests"
    ]

[data.fields]
srnumber = ""
requesttype = ""
status = ""
actiontaken = ""
createddate = ""
updateddate = ""
servicedate = ""
closeddate = ""
requestsource = ""
anonymous = ""
mobileos = ""
owner = ""
nc = "integer"
ncname = ""
policeprecinct = ""
apc = ""
assignto = ""
cd = "integer"
cdmember = ""
address = ""
zipcode = ""
latitude = ""
longitude = ""
