version: '3.4'

services:
  backend:
   # build:
   #   context: ../server
   image: docker.pkg.github.com/hackforla/311-data/backend:efdd561e412d78a9a97a074abdb3b73f28e108ce
   restart: always
   container_name: "311-backend"
   environment:
     DB_CONNECTION_STRING: postgresql://REDACTED:REDACTED@db:5432/postgres
     PROJECT_URL: REDACTED
     GITHUB_TOKEN: REDACTED
     TOKEN: REDACTED
     REDIS_URL: redis://redis:6379
   ports:
     - 5000:5000

  frontend:
   build:
     context: ..
   network_mode: host
   image: docker.pkg.github.com/hackforla/311-data/frontend:efdd561e412d78a9a97a074abdb3b73f28e108ce
   restart: always
   container_name: "311-frontend"
   environment:
     REACT_APP_MAPBOX_TOKEN: REDACTED
     DB_URL: http://localhost:5000
     BASE_URL: ''
   ports:
     - 3000:3000

  db:
    image: postgres
    restart: always
    container_name: "311-postgres"
    environment:
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_USER: REDACTED
    ports:
      - 5432:5432
    volumes:
      - backend_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: "postgres-dashboard"
    ports:
      - 8080:8080

  redis:
    build:
      context: ../redis
    container_name: "311-redis"
    expose:
      - 6379

  rebrow:
    image: marian/rebrow
    links:
      - redis:redis
    container_name: "redis-dashboard"
    ports:
      - 5001:5001

volumes:
  backend_data:
