name: CI_Frontend

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Setup environment
      run: |
        echo MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }} > .env
        echo MAPBOX_STREETS_URL=${{ secrets.MAPBOX_STREETS_URL }} > .env
        echo MAPBOX_SATELLITE_URL=${{ secrets.MAPBOX_SATELLITE_URL }} > .env
        echo API_URL=${{ secrets.API_URL_PROD }} >> .env
        echo MIXPANEL_ENABLED=${{ secrets.MIXPANEL_ENABLED }} >> .env
        echo MIXPANEL_TOKEN_PROD=${{ secrets.MIXPANEL_TOKEN_PROD }} >> .env
        echo MIXPANEL_TOKEN_DEV=${{ secrets.MIXPANEL_TOKEN_DEV }} >> .env
    - name: Build project
      run: npm run build
    - name: Run Tests
      run: npm run test -- --coverage
