name: MasterDeployCI
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tf_version: 'latest'
  tf_working_dir: './Orchestration/terraform'
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rebuild sass
      run: npm rebuild node-sass
    - name: Install Packages
      run: npm install
    - name: Setup environment
      run: |
        echo REACT_APP_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }} > .env
        echo DB_URL=${{ secrets.DB_URL }} >> .env
        echo GITHUB_SHA=${{ github.sha }} >> .env
    - name: Build project
      run: npm run build
    - name: Run Tests
      run: export CI=true && npm run test -- --coverage
    - name: Deploy to GH pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REACT_APP_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        DB_URL: ${{ secrets.DB_URL }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
 #   - name: Terraform Init
 #     uses: hashicorp/terraform-github-actions@master
 #     with:
 #       tf_actions_version: ${{ env.tf_version }}
 #       tf_actions_working_dir: ${{ env.tf_working_dir }}
 #       tf_actions_subcommand: 'init'
 #   - name: Terraform Validate
 #     uses: hashicorp/terraform-github-actions@master
 #     with:
 #       tf_actions_version: ${{ env.tf_version }}
 #       tf_actions_working_dir: ${{ env.tf_working_dir }}
 #       tf_actions_subcommand: 'validate'
 #       tf_actions_comment: true
    # - name: Terraform Apply
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: ${{ env.tf_version }}
    #     tf_actions_working_dir: ${{ env.tf_working_dir }}
    #     tf_actions_subcommand: 'apply'
    #     tf_actions_comment: true
