name: Deploy_Backend_Dev

on:
  push:
    branches:
      - dev
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run deploy script on AWS dev
        uses: appleboy/ssh-action@master
        with:
          username: ec2-user
          host: ${{ secrets.AWS_DEV_HOST }}
          key: ${{ secrets.AWS_DEV_PRIVATE_KEY }}
          script: |
            set -e
            cd 311-data/server
            git pull
            echo GITHUB_SHA=${{ github.sha }} >> .env
            docker-compose build api
            docker-compose up --no-deps -d api
