name: Dev_CI_Backend

on:
  pull_request:
    paths:
      - 'server/**'

defaults:
  run:
    shell: bash
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and Run Api
        run: |
          cp .env.example .env
          echo SOCRATA_TOKEN=${{ secrets.SOCRATA_TOKEN }} >> .env
          docker-compose up --no-start api
          docker-compose run api python bin/db_seed.py --years 2020 --rows 500 --reset
          docker-compose up -d api

      - name: Linting
        run: docker-compose run api flake8

      - name: Unit Tests
        run: docker-compose run api pytest

      - name: Postman Tests
        run: chmod +x postman/test.sh && postman/test.sh
